[package]
name = "implement-a-vfs"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = "0.12.4"
sqlite-wasm-rs = { path = "../../sqlite-wasm-rs", default-features = false, features = ["precompiled"] }
wasm-bindgen-test = "0.3.50"

